### ISSUE TITLE
bug [line factor]

### ISSUE THREAD

**Issue by minxuanjun** [url-kaist/UV-SLAM#2]
I find that you use auto differentiation provided by ceres to realize line factor. But you don't consider the correctness of pose local Parameterization. Because in imu and projection cost function,  VINS-Mono directly solves error jacobian w.r.t pose local par parameterization. However, the jacobian of auto differentiation is w.r.t pose full parameterization.

**Comment by tp02134** [comment]
Thank you for your valuable comment.
We are trying to apply local parameterization to line and vanishing point factors.
Thank you
