### ISSUE TITLE
Use ceres to automatically derive the Jacobian of the line

### ISSUE THREAD

**Issue by NEU-LC** [url-kaist/UV-SLAM#3]
Hello，

Thanks for your contribution!

The Jacobian of the reprojection error of the line w.r.t. pose is be automatically derived. But in my opinion, If we use the automatic derivation of ceres, the corresponding
line reprojection Jacobian matrix with respect to the pose is obtained in terms of imu pose should be the global parameters space(4+3, quaternion + trans). In other words, the global parameter dimension of the quaternion should be 4, while the actual optimization space should be 3. Therefore, if the quaternion is automatically derived, then in the `pose_local_parameterzation.cpp`, the jacobian w.r.t. quaternion in terms of theta should not be the identity matrix.
``` c++
bool PoseLocalParameterization::ComputeJacobian(const double *x, double *jacobian) const
{
    Eigen::Map<Eigen::Matrix<double, 7, 6, Eigen::RowMajor>> j(jacobian);
    j.topRows<6>().setIdentity();
    j.bottomRows<1>().setZero();

    return true;
}
```

Best wishes.

**Comment by tp02134** [comment]
Thank you for your valuable comment.
We are trying to apply local parameterization to line and vanishing point factors.
Thank you
