### ISSUE TITLE
roslaunch vins_estimator keeps me waiting

### ISSUE THREAD

**Issue by C-H-Chien** [url-kaist/UV-SLAM#9]
Hi! My friend and I are very new to ROS and are trying to follow the instruction of launching vins_estimator by
`roslaunch uv_slam euroc.launch`
However, the progress is stuck at the point of "waiting for img and imu..."
![Screenshot 2022-11-20 161324](https://user-images.githubusercontent.com/43362125/202926620-c762e8ef-664a-4a55-96d8-17204604d04a.png)

Do I need to install VINS-Mono to have a successful roslaunch on vins_estimator? Or what could I do to solve this issue?
Thank you!

**Comment by tp02134** [comment]
Thank you for your interest.
Did you play the bag file (ex. EuRoC)?

**Comment by C-H-Chien** [comment]
Hi @tp02134 ! Thank you very much for the answer. I apologize for this silly question as I am very new to ROS. 
I was thinking that I have to wait `roslaunch uv_slam euroc.launch` to complete before running the next command but then I realized that it is waiting for me to play the rosbag. Now the code is working. Thank you again for your kind help!
